language: rust
os:
  - linux
  - osx
  - windows
dist: xenial

rust:
  - stable
  - beta
  - nightly

branches:
  - develop
  - master

cache: cargo

jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true

script:
  - cargo build --verbose
  - cargo test --verbose