[package]
name = "rust-gpx"
version = "0.1.0"
authors = ["Paulius Gudonis <pg@neqsoft.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.2.10"