[package]
name = "rust-gpx-cli"
version = "0.1.0"
authors = ["Paulius Gudonis <pg@neqsoft.com>"]
readme = "README.md"
repository = "https://github.com/nakkht/rust-gpx-cli"
license = "MIT"
edition = "2018"

[dependencies]
structopt = "0.3.20"
quick-xml = "0.20.0"
chrono = "0.4.19"