[package]
name = "rust-gpx"
version = "0.1.0"
authors = ["Paulius Gudonis <pg@neqsoft.com>"]
readme = "README.md"
repository = "https://github.com/nakkht/rust-gpx"
license = "MIT"
edition = "2018"

[dependencies]
structopt = "0.2.10"